accelerator: null
accumulate_grad_batches: null
act_type: PReLU
amp_backend: native
amp_level: null
audio_sample_rate: 22050
augment: true
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
ballroom_annot_dir: ../labeled_data/ballroom/label
ballroom_audio_dir: ../labeled_data/ballroom/data
batch_size: 16
beatles_annot_dir: ../labeled_data/beatles/label
beatles_audio_dir: ../labeled_data/beatles/data
benchmark: null
causal: false
channel_growth: 32
channel_width: 32
check_val_every_n_epoch: 1
dataset: ballroom
default_root_dir: lightning_logs/full
detect_anomaly: false
deterministic: null
devices: null
dilation_growth: 8
dry_run: false
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
eval_length: 2097152
fast_dev_run: false
gpus: 1
gradient_clip_algorithm: null
gradient_clip_val: null
grouped: false
hainsworth_annot_dir: ../labeled_data/hains/label
hainsworth_audio_dir: ../labeled_data/hains/data
inference_mode: true
ipus: null
kernel_size: 15
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
lr: 0.01
max_epochs: 100
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_type: dstcn
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
nblocks: 8
ninputs: 1
norm_type: BatchNorm
noutputs: 2
nparams: 2
num_examples: 4
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 12
overfit_batches: 0.0
patience: 10
plugins: null
precision: 32
preload: true
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
rwc_popular_annot_dir: ../labeled_data/rwc_popular/label
rwc_popular_audio_dir: ../labeled_data/rwc_popular/data
save_dir: null
shuffle: true
skip_connections: false
stack_size: 4
strategy: null
stride: 2
sync_batchnorm: false
target_factor: 256
target_sample_rate: 86.1328125
tpu_cores: null
track_grad_norm: -1
train_fraction: 1.0
train_length: 2097152
train_subset: train
val_check_interval: null
val_subset: val
